### ISSUE TITLE
Blog y seminarios

### ISSUE THREAD

**Issue by hbottialsina** [GUIAD-COVID/website-GUIAD#1]
Hola esta buenazo, creo que se podría incluir un Blog y como costumbre cada artículo que se discuta en el seminario común lo podamos comentar en él.

**Comment by lorenae** [comment]
Hola Horacio.
Gracias!
La sección Novedades es un blog https://guiad-covid.github.io/#posts, ahí se pueden escribir posts que inclusive pueden incluir fórmulas, gráficos, etc. Para ver ejemplos de lo que se puede hacer mirate [acá](https://academic-demo.netlify.com/#posts)
