### ISSUE TITLE
detalles a corregir

### ISSUE THREAD

**Issue by mfariello** [GUIAD-COVID/website-GUIAD#3]
Doble paréntesis en el medio del segundo párrafo ->  va uno

Corregir en el disclaimer Todo lo aquí presentado es a título personal DE por quienes firman las notas y participan en el proyecto, y no necesariamente reflejaN la opinión de las instituciones a las que pertenecen. (esa N no va)

Zaida Arteta - MédicA

Sacarle a Nacho el Universidad de Harvard -> afuera

En la parte de enlaces, el segundo y el cuarto no dicen quién los mantiene. 
Agregar al IIBCE que también armó un sitio sobre covid. 

En alguno vi facultad con minúscula y en otros con mayúscula

**Comment by mfariello** [comment]
Agrego más: 
- al principio del 2do párrafo creo que es “dadas” en lugar de “dada”;
- también en el 2do párrafo, se definen como grupo de “científicos”, vean si no les parece mejor decir “investigadores”.

**Comment by mfariello** [comment]
A modo de recordatorio:
-cambiar links por enlaces 
-cambiar PhD por Dr

**Comment by gmonce** [comment]
- Arreglado el paréntesis
- Corregido el disclaimer
- Cambié los Phd. por Dr.
- Sacado Harvard. 
- Cambiados los facultad con minúscula en el quiénes somos
- Cambié links por enlaces en la presentación

**Comment by gmonce** [comment]
- Cambié link por enlace en recursos
- Agregué quiénes mantienen los repositorios
- Puse al IIBCE (y agregué una sección "Uruguay")

**Comment by gmonce** [comment]
Listo según commit 78850213b396167d5c3387dd283ea17c4e946218
