### ISSUE TITLE
Agregar sección en qué puedo ayudar

### ISSUE THREAD

**Issue by mfariello** [GUIAD-COVID/website-GUIAD#6]
(Texto mártir)
Todos los investigadores queremos ayudar. Este artículo, nos explica todas las maneras en que podemos hacerlo. 
https://www.nature.com/articles/s42254-020-0175-7
Destacamos la importancia de cumplir como comunicadores y traductores responsables de lo que entendemos a la sociedad.

**Comment by gmonce** [comment]
Les parece que lo ponga como un post?

**Comment by gmonce** [comment]
También podríamos ponerlo en "Recursos externos"

**Comment by gmonce** [comment]
https://twitter.com/guiad_covid19/status/1250822372371902470
